function [fitresult, gof] = becfit(xdata, xf)
    %CREATEFIT(XDATA,XF)
    %  Create a fit.
    %
    %  Data for 'untitled fit 1' fit:
    %      X Input : xdata
    %      Y Output: xf
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 30-Apr-2014 14:22:17
    
    
    %% Fit: 'untitled fit 1'.
    [xData, yData] = prepareCurveData( xdata, xf );
    
    [peak,index]=max(xf);
    
    % Set up fittype and options.
    ft = fittype( 'nth*gbec(3/2,exp(-(x-x0).^2/(2*sxth^2)),50)+nbec*max(0,1-(x-x0).^2/(sxbec^2))', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.Lower = [0 0 0 0 0];
    opts.StartPoint = [peak peak/10 length(xdata)/100 length(xdata)/20 xData(index)]; %in the order: [nbec nth sxbec sxth x0]
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    
%     % Plot fit with data.
%     figure( 'Name', 'untitled fit 1' );
%     h = plot( fitresult, xData, yData );
%     legend( h, 'xf vs. xdata', 'untitled fit 1', 'Location', 'NorthEast' );
%     % Label axes
%     xlabel( 'xdata' );
%     ylabel( 'xf' );
%     grid on
%     
    
